name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install black flake8

      - name: Run Linter
        run: |
          black --check my-secure-app/app/
          flake8 my-secure-app/app/

      - name: Run tests
        run: |
          # Aquí puedes usar pytest o unittest
          echo "No hay tests aún"

      # 🔐 Trivy FS Scan (escaneo de código fuente)
      - name: Scan with Trivy (File System)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './'

      # 🐳 Construcción y escaneo de imagen Docker (opcional)
      - name: Build Docker image
        run: docker build -t my-secure-app .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'my-secure-app'
